### ISSUE TITLE
Автоматизация тестов для основных операторов

### ISSUE THREAD

**Issue by Mozzarella123** [Students-of-the-city-of-Kostroma/16ISa#27]
Автоматизация тестов для основных story #20 

- [x] №1.1 Написать тесты для части сценариев для основных операторов #35 

- [x] №2.1 Написать тесты для части сценариев для основных операторов #37 

- [x] №3.1 Написать тесты для части сценариев для основных операторов #39 

- [x] Сформировать отчет о проведении тестов по сценариям для основных операторов #42
