### ISSUE TITLE
Автоматизация тестов для операторов умножения и деления

### ISSUE THREAD

**Issue by Mozzarella123** [Students-of-the-city-of-Kostroma/16ISa#28]
Автоматизация тестов для story #21 

- [x] №1.2 Написать тесты для части сценариев для операторов умножения и деления #36 

- [x] №2.2 Написать тесты для части сценариев для операторов умножения и деления #38 

- [x] №3.2 Написать тесты для части сценариев для операторов умножения и деления  #40 

- [ ] Сформировать отчет о проведении тестов по сценариям для операторов умножения и деления #41
